# Generated by Django 5.0.6 on 2024-06-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.PositiveIntegerField(verbose_name='SID')),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=100)),
                ('Faculty', models.CharField(max_length=50, verbose_name='Faculty')),
                ('gpa', models.FloatField(verbose_name='GPA')),
            ],
        ),
    ]
