# Generated by Django 5.0.6 on 2024-06-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_faculty_student_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_number',
        ),
    ]
