# Generated by Django 5.0.6 on 2024-06-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_student_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.CharField(choices=[('BIT', 'Bachelor in Information Technology'), ('BCS', 'Bachelor in Computer Science'), ('BBA', 'Bachelor in Business Administration'), ('BCA', 'Bachelor in Computer Architecture'), ('BHM', 'Bachelor in Hotel Management')], max_length=50, verbose_name='Faculty'),
        ),
    ]
